# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2017-06-28 13:51
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('public_administration_structure_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ActionsForWaterPointProblem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action_code', models.CharField(max_length=10)),
                ('action_description', models.CharField(max_length=500)),
            ],
        ),
        migrations.CreateModel(
            name='CommuneLevelReporters',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reporter_phone_number', models.CharField(max_length=20)),
                ('reporter_name', models.CharField(max_length=100)),
                ('date_registered', models.DateTimeField(auto_now_add=True)),
                ('commune', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='public_administration_structure_app.Commune')),
            ],
        ),
        migrations.CreateModel(
            name='ExpectedBudgetExpenditureAndAnnualBudget',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('annual_badget', models.IntegerField()),
                ('expected_annual_expenditure', models.IntegerField()),
                ('reporting_year', models.IntegerField()),
                ('reception_date', models.DateTimeField(auto_now_add=True)),
                ('commune', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='public_administration_structure_app.Commune')),
            ],
        ),
        migrations.CreateModel(
            name='ExpenditureCategory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('expenditure_category_name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='LocalLevelReporter',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reporter_phone_number', models.CharField(max_length=20)),
                ('reporter_name', models.CharField(max_length=50)),
                ('date_registered', models.DateTimeField(auto_now_add=True)),
                ('colline', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='public_administration_structure_app.Colline')),
            ],
        ),
        migrations.CreateModel(
            name='MonthlyExpenditure',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('expenditure_amount', models.IntegerField()),
                ('reporting_year', models.IntegerField()),
                ('reporting_month', models.IntegerField()),
                ('reception_date', models.DateTimeField(auto_now_add=True)),
                ('commune', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='public_administration_structure_app.Commune')),
                ('expenditure', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='amazi_meza_app.ExpenditureCategory')),
            ],
        ),
        migrations.CreateModel(
            name='MonthlyIncome',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_income', models.IntegerField()),
                ('reporting_year', models.IntegerField()),
                ('reporting_month', models.IntegerField()),
                ('reception_date', models.DateTimeField(auto_now_add=True)),
                ('commune', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='public_administration_structure_app.Commune')),
            ],
        ),
        migrations.CreateModel(
            name='NumberOfHouseHold',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number_of_house_holds', models.IntegerField()),
                ('number_of_vulnerable_house_holds', models.IntegerField()),
                ('reporting_year', models.IntegerField()),
                ('reporting_month', models.IntegerField()),
                ('reception_date', models.DateTimeField(auto_now_add=True)),
                ('commune', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='public_administration_structure_app.Commune')),
            ],
        ),
        migrations.CreateModel(
            name='NumberOfWaterNetworkProblems',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number_of_water_network_problems', models.IntegerField()),
                ('number_of_days', models.IntegerField()),
                ('reporting_year', models.IntegerField()),
                ('reporting_month', models.IntegerField()),
                ('reception_date', models.DateTimeField(auto_now_add=True)),
                ('commune', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='public_administration_structure_app.Commune')),
            ],
        ),
        migrations.CreateModel(
            name='NumberOfWaterPointCommittee',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number_of_water_point_committees', models.IntegerField()),
                ('reporting_year', models.IntegerField()),
                ('reporting_month', models.IntegerField()),
                ('reception_date', models.DateTimeField(auto_now_add=True)),
                ('commune', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='public_administration_structure_app.Commune')),
            ],
        ),
        migrations.CreateModel(
            name='NumberOfWaterSourceEndPoint',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('existing_number', models.IntegerField()),
                ('functional_number', models.IntegerField()),
                ('reporting_year', models.IntegerField()),
                ('reporting_month', models.IntegerField()),
                ('reception_date', models.DateTimeField(auto_now_add=True)),
                ('commune', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='public_administration_structure_app.Commune')),
            ],
        ),
        migrations.CreateModel(
            name='WaterNetWork',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('water_network_name', models.CharField(max_length=50)),
                ('date_registered', models.DateTimeField(auto_now_add=True)),
                ('length_of_network', models.IntegerField()),
                ('commune', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='public_administration_structure_app.Commune')),
                ('reporter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='amazi_meza_app.CommuneLevelReporters')),
            ],
        ),
        migrations.CreateModel(
            name='WaterNetworkProblemType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('water_network_problem_type_name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='WaterPointProblem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('days', models.IntegerField()),
                ('problem_solved', models.BooleanField(default=False)),
                ('case_of_diarrhea', models.BooleanField(default=False)),
                ('action_taken', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='amazi_meza_app.ActionsForWaterPointProblem')),
            ],
        ),
        migrations.CreateModel(
            name='WaterPointProblemTypes',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('problem_type_name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='WaterPointType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='WaterSourceEndPoint',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('water_point_name', models.CharField(max_length=50)),
                ('date_registered', models.DateTimeField(auto_now_add=True)),
                ('colline', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='public_administration_structure_app.Colline')),
                ('network', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='amazi_meza_app.WaterNetWork')),
                ('reporter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='amazi_meza_app.LocalLevelReporter')),
                ('water_point_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='amazi_meza_app.WaterPointType')),
            ],
        ),
        migrations.AddField(
            model_name='waterpointproblem',
            name='problem',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='amazi_meza_app.WaterPointProblemTypes'),
        ),
        migrations.AddField(
            model_name='waterpointproblem',
            name='water_point',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='amazi_meza_app.WaterSourceEndPoint'),
        ),
        migrations.AddField(
            model_name='numberofwatersourceendpoint',
            name='water_point_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='amazi_meza_app.WaterPointType'),
        ),
        migrations.AddField(
            model_name='numberofwaternetworkproblems',
            name='water_network_problem_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='amazi_meza_app.WaterNetworkProblemType'),
        ),
    ]
