# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2017-07-04 10:17
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('public_administration_structure_app', '0001_initial'),
        ('amazi_meza_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TemporaryLocalLevelReporter',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reporter_phone_number', models.CharField(max_length=20)),
                ('reporter_name', models.CharField(max_length=50)),
                ('date_registered', models.DateTimeField(auto_now_add=True)),
                ('colline', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='public_administration_structure_app.Colline')),
            ],
        ),
    ]
