# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2017-07-17 06:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('amazi_meza_app', '0003_temporarycommunelevelreporters'),
    ]

    operations = [
        migrations.AddField(
            model_name='waternetwork',
            name='water_network_code',
            field=models.CharField(default='', max_length=10),
            preserve_default=False,
        ),
    ]
