# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2017-07-18 19:02
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('amazi_meza_app', '0004_waternetwork_water_network_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='waterpointtype',
            name='priority',
            field=models.IntegerField(default=1, help_text='La plus petite valeur est 1'),
        ),
    ]
