# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2017-07-19 09:43
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('amazi_meza_app', '0005_waterpointtype_priority'),
    ]

    operations = [
        migrations.AddField(
            model_name='numberofwatersourceendpoint',
            name='report_type',
            field=models.CharField(default=1, max_length=50),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='numberofwatersourceendpoint',
            name='existing_number',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='numberofwatersourceendpoint',
            name='functional_number',
            field=models.IntegerField(null=True),
        ),
    ]
