# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2017-07-26 13:06
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('amazi_meza_app', '0008_auto_20170726_1118'),
    ]

    operations = [
        migrations.AddField(
            model_name='expenditurecategory',
            name='priority',
            field=models.IntegerField(default=1, help_text='La plus petite valeur est 1'),
        ),
    ]
