# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2017-07-26 14:06
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('amazi_meza_app', '0009_expenditurecategory_priority'),
    ]

    operations = [
        migrations.RenameField(
            model_name='numberofwaternetworkproblems',
            old_name='water_network_problem_type',
            new_name='most_frequent_water_network_problem_type',
        ),
    ]
