# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2017-10-10 13:27
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('amazi_meza_app', '0012_waterpointproblem_report_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='waterpointproblemtypes',
            name='problem_type_description',
            field=models.CharField(default='', max_length=50),
        ),
    ]
