# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2017-10-18 09:26
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('amazi_meza_app', '0016_waterpointproblem_resolve_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='waterpointproblem',
            name='resolve_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
