# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2017-10-25 12:20
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('amazi_meza_app', '0017_auto_20171018_1126'),
    ]

    operations = [
        migrations.CreateModel(
            name='WaterPointProblemResolver',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('resolver_level_code', models.CharField(max_length=10)),
                ('resolver_level_name', models.CharField(max_length=100)),
            ],
        ),
        migrations.AddField(
            model_name='waterpointproblem',
            name='resolved_at',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='amazi_meza_app.WaterPointProblemResolver'),
        ),
    ]
