# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2017-10-26 09:54
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('amazi_meza_app', '0018_auto_20171025_1420'),
    ]

    operations = [
        migrations.CreateModel(
            name='Setting',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('setting_code', models.CharField(max_length=20)),
                ('setting_name', models.CharField(max_length=200)),
                ('setting_value', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='TimeMeasuringUnit',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=4)),
                ('description', models.CharField(max_length=20)),
            ],
        ),
        migrations.AddField(
            model_name='setting',
            name='time_measuring_unit',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='amazi_meza_app.TimeMeasuringUnit'),
        ),
    ]
