# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2018-06-28 12:55
from __future__ import unicode_literals

from django.db import migrations
import djgeojson.fields


class Migration(migrations.Migration):

    dependencies = [
        ('amazi_meza_app', '0019_auto_20171026_1154'),
    ]

    operations = [
        migrations.AddField(
            model_name='watersourceendpoint',
            name='geom',
            field=djgeojson.fields.PointField(null=True),
        ),
    ]
